# Runs tests on pull requests for main
permissions: read-all
name: Presubmit
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install nox
      run: pip install -e .[dev]

    - name: Check formatting
      run: nox -s lint
    - name: Run tests
      run: nox -s tests-${{ matrix.python-version }}
